inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  SuggestExtensions: false

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-thread_safety


Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

