# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Lint & Tests"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install -y ruby-dev build-essential git libvips pkg-config libproj-dev proj-bin
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
      - name: Install eslint
        run: npm install
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel
      - name: Lint Javascript
        run: npm run lint:js
      - name: Lint CSS
        run: npm run lint:css

  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
        - 27017:27017
    env:
      RAILS_ENV: test
      COVERAGE: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install -y ruby-dev build-essential git libvips pkg-config libproj-dev proj-bin
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Run tests
        id: rspec
        run: |
          echo "::set-output name=exit_code::$(bin/rspec || echo $?)"
        shell: bash
      - name: Upload screenshots
        if: steps.rspec.outputs.exit_code != '0'
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./tmp/capybara
      - name: Upload logs
        if: steps.rspec.outputs.exit_code != '0'
        uses: actions/upload-artifact@v2
        with:
          name: rails-logs
          path: ./log/test.log
      - name: Coveralls
        uses: coverallsapp/github-action@v2
