# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Lint & Tests"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update OS
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y libproj-dev proj-bin
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install npm dependencies
        run: npm install
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel
      - name: Lint Javascript
        run: npm run lint:js
      - name: Lint CSS
        run: npm run lint:css

  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
        - 27017:27017
    env:
      RAILS_ENV: test
      COVERAGE: true
      ADMIN_USER: 'test'
      ADMIN_PW: 'test'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update OS
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y ruby-dev build-essential git libvips pkg-config libproj-dev proj-bin
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        id: rspec
        run: |
          bin/rspec --pattern "spec/**/*_spec.rb,engines/**/*_spec.rb"
        shell: bash
      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ./tmp/capybara
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: rails-logs
          path: ./log/test.log
      - name: Coveralls
        uses: coverallsapp/github-action@v2
